CREATE DATABASE BANK;
USE BANK;

CREATE TABLE bank_customer(
customer_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
age INT(3) NOT NULL,
gender VARCHAR(100) NOT NULL,
city VARCHAR(100) NOT NULL,
mobile VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
account_type VARCHAR(50) NOT NULL,
balance DECIMAL(10,2) NOT NULL
);

SELECT * FROM bank_customer;
